//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameLogBack.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_pl {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_pl() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GameLogBack.Resources.SharedResource_pl", typeof(SharedResource_pl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string IncorrectDataOfLogin {
            get {
                return ResourceManager.GetString("IncorrectDataOfLogin", resourceCulture);
            }
        }
        
        internal static string ExpiredRefreshToken {
            get {
                return ResourceManager.GetString("ExpiredRefreshToken", resourceCulture);
            }
        }
        
        internal static string UsernameAlreadyExist {
            get {
                return ResourceManager.GetString("UsernameAlreadyExist", resourceCulture);
            }
        }
        
        internal static string EmailAlreadyTaken {
            get {
                return ResourceManager.GetString("EmailAlreadyTaken", resourceCulture);
            }
        }
        
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        internal static string IncorrectVerificationCode {
            get {
                return ResourceManager.GetString("IncorrectVerificationCode", resourceCulture);
            }
        }
        
        internal static string VerificationCodeNotFound {
            get {
                return ResourceManager.GetString("VerificationCodeNotFound", resourceCulture);
            }
        }
        
        internal static string ExpiredVerificationCode {
            get {
                return ResourceManager.GetString("ExpiredVerificationCode", resourceCulture);
            }
        }
        
        internal static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        internal static string RecoveryCodeIsIncorrect {
            get {
                return ResourceManager.GetString("RecoveryCodeIsIncorrect", resourceCulture);
            }
        }
        
        internal static string RecoveryCodeHasExpired {
            get {
                return ResourceManager.GetString("RecoveryCodeHasExpired", resourceCulture);
            }
        }
        
        internal static string CategoryNotFound {
            get {
                return ResourceManager.GetString("CategoryNotFound", resourceCulture);
            }
        }
        
        internal static string CategoryWithThisNameAlreadyExists {
            get {
                return ResourceManager.GetString("CategoryWithThisNameAlreadyExists", resourceCulture);
            }
        }
        
        internal static string ExistGameWithThisCategory {
            get {
                return ResourceManager.GetString("ExistGameWithThisCategory", resourceCulture);
            }
        }
        
        internal static string GameNotFound {
            get {
                return ResourceManager.GetString("GameNotFound", resourceCulture);
            }
        }
        
        internal static string GameWithThisNameAlreadyExists {
            get {
                return ResourceManager.GetString("GameWithThisNameAlreadyExists", resourceCulture);
            }
        }
    }
}
