// <auto-generated />
using System;
using GameLogBack.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameLogBack.Migrations
{
    [DbContext(typeof(GameLogDbContext))]
    [Migration("20250726193052_ChangeLimitLengthForCodeInCodeRecoveryPasswordTable")]
    partial class ChangeLimitLengthForCodeInCodeRecoveryPasswordTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameLogBack.Entities.CodeConfirmUsers", b =>
                {
                    b.Property<string>("CodeId")
                        .HasColumnType("text")
                        .HasColumnName("confirm_code_id");

                    b.Property<string>("Code")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("confirm_code");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("CodeId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("confirm_confirm_users", (string)null);
                });

            modelBuilder.Entity("GameLogBack.Entities.CodeRecoveryPassword", b =>
                {
                    b.Property<string>("CodeId")
                        .HasColumnType("text")
                        .HasColumnName("recovery_code_id");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("recovery_code");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("CodeId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("code_recovery_password", (string)null);
                });

            modelBuilder.Entity("GameLogBack.Entities.RefreshTokenInfo", b =>
                {
                    b.Property<string>("RefreshTokenId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("refresh_token_id");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("refresh_token_info", (string)null);
                });

            modelBuilder.Entity("GameLogBack.Entities.UserLogins", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("GameLogBack.Entities.Users", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("firstname");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lastname");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_email");

                    b.HasKey("UserId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("GameLogBack.Entities.CodeConfirmUsers", b =>
                {
                    b.HasOne("GameLogBack.Entities.Users", "User")
                        .WithOne("CodeConfirm")
                        .HasForeignKey("GameLogBack.Entities.CodeConfirmUsers", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameLogBack.Entities.CodeRecoveryPassword", b =>
                {
                    b.HasOne("GameLogBack.Entities.Users", "User")
                        .WithOne("CodeRecoveryPassword")
                        .HasForeignKey("GameLogBack.Entities.CodeRecoveryPassword", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameLogBack.Entities.RefreshTokenInfo", b =>
                {
                    b.HasOne("GameLogBack.Entities.Users", "User")
                        .WithOne("RefreshTokens")
                        .HasForeignKey("GameLogBack.Entities.RefreshTokenInfo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameLogBack.Entities.UserLogins", b =>
                {
                    b.HasOne("GameLogBack.Entities.Users", "User")
                        .WithOne("UserLogins")
                        .HasForeignKey("GameLogBack.Entities.UserLogins", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameLogBack.Entities.Users", b =>
                {
                    b.Navigation("CodeConfirm");

                    b.Navigation("CodeRecoveryPassword");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserLogins");
                });
#pragma warning restore 612, 618
        }
    }
}
